sudo: required
services:
  -docker

before_install:
  - docker build -t sarithf/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sarithf/react-test npm test

after_success:
  - docker build-t sarithf/multi-client ./client
  - docker build-t sarithf/multi-nginx ./nginx
  - docker build-t sarithf/multi-server ./server
  - docker build-t sarithf/multi-worker ./worker
  #login to docker hub CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take images and push them to docker hub
  - docker push sarithf/multi-container:sarithf/multi-client
  - docker push sarithf/multi-container:sarithf/multi-nginx
  - docker push sarithf/multi-container:sarithf/multi-server
  - docker push sarithf/multi-container:sarithf/multi-worker


